### ISSUE TITLE
Add a NEWNYM tool for Workstation

### ISSUE THREAD

**Issue by annonn** [Whonix/Whonix#102]
Please see this ticket: https://trac.torproject.org/projects/tor/ticket/9442

It would be nice to have a shortcut/tool somewhere in Whonix-Workstation to send a NEWNYM command to use new circuits. As explained in the ticket, New Identity isn't the same as NEWNYM because user may not want to close the tabs / delete the session but instead use fresh circuits to pass through an IP ban, get rid of a slow node (and find a faster one), or quickly change the nodes against identity correlation.

Can we add a shortcut/tool and documentation to send this command so the users will not need to switch the virtual machines to manually do this. Even if this function gets added to Tor Browser or not.

Because this is not only related to Tor Browser, all of the applications in Workstation can benefit from this. It may also help when we have (remote) access on Workstation but not on Gateway, correct? (For remote access or using in scripts, is there currently a command for this to use on command-line?)

Also: This feature could be added to the comparison table. If NEWNYM won't be added to next major Tor Browser release, it will not be possible to use this command for TBB (since Vidalia got deleted). It is possible on Gateway, and hopefully on Workstation too after this issue gets closed.

**Comment by JasonJAyalaP** [comment]
https://phabricator.whonix.org/T90
