### ISSUE TITLE
use /etc/network/if-pre-up.d/ instead of /etc/network/interfaces to load Whonix's firewall as soon as Whonix is based on Debian Jessie

### ISSUE THREAD

**Issue by adrelanos** [Whonix/Whonix#136]
Debian bug [#700811: interface comes up even if a script in /etc/network/if-pre-up.d/ fails](http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=700811) has been fixed.

It would be better to drop Whonix-Workstation's (optional) and Whonix-Gateway's firewall load hook in /etc/network/if-pre-up.d/ than doing what we're doing right now (using pre-up in /etc/network/interfaces). This would make /etc/network/interfaces cleaner, easier to port and more difficult for users to remove pre-up from /etc/network/interfaces and shoot their own feet.

We have to wait until Debian Jessie gets stable, because this bug ix not fixed in Debian Wheezy.

**Comment by JasonJAyalaP** [comment]
https://phabricator.whonix.org/T68
