### ISSUE TITLE
Internationalization Support / Whonix Greeter / Language

### ISSUE THREAD

**Issue by adrelanos** [Whonix/Whonix#15]
When installing stock Debian, the user can choose the local language in Debian Installer. This goes for most operating systems. Whonix is different, mainly used by people who import Whonix as virtual machine images, which are preinstalled (Whonix is a Debian derivative).

There is currently no Whonix Greeter, which asks, which language the user wants to use. Upon choosing, we could install the appropriate language debian packages.

Maybe we can we fork Tails Greeter so the user can choose which language packages to install once Whonix VMs have been imported? Other options? Create one from scratch?

(Shipping all available language packs would make the VM images unnecessarily bigger and updates, which go over Tor, waste a lot space and take a lot longer.)

(Whonix's torbrowser download script already supports downloading non-English languages. [Micah's torbrowser downloader](https://github.com/micahflee/torbrowser-launcher/) will support that as well. The user just does not get asked by Whonix, which language she wants to use.)

**Comment by JasonJAyalaP** [comment]
https://phabricator.whonix.org/T72
