### ISSUE TITLE
drop uwt as soon as torsocks gets native stream isolation support

### ISSUE THREAD

**Issue by adrelanos** [Whonix/Whonix#16]
Depending on [\#8053](https://trac.torproject.org/projects/tor/ticket/8053 "enhancement: add stream isolation support to torsocks (needs_review)") "add stream isolation support to torsocks) uwt becomes redundant. Looks like this feature may come, therefore wait how it develops and help upstream testing.

When that happens /usr/local/bin/uwtwrapper should use torsocks instead of uwt. And uwt should be removed.

(torsocks is written in C: so anyone capable for speaking C could help upstream reviewing the feature.)

**Comment by JasonJAyalaP** [comment]
https://phabricator.whonix.org/T65
