### ISSUE TITLE
default socksification of ssh, wget, curl, etc. is confusing for local connections

### ISSUE THREAD

**Issue by adrelanos** [Whonix/Whonix#164]
Many advanced users are confused by Whonix's socksification of default applications such as ssh, wget, curl, etc. (For stream isolation https://www.whonix.org/wiki/Stream_Isolation) by `uwt`.

When they do `ssh 192.168.0.11` ssh will go through a Tor SocksPort, which won't be possible for local connections. It will result in the following error message.

```libtorsocks(12021): connect: Connection is to a local address (192.168.0.11), may be a TCP DNS request to a local DNS server so have to reject to be safe. Please report a bug to http://code.google.com/p/torsocks/issues/entry if this is preventing a program from working properly with torsocks```

Maybe in `~/.bashrc` (as terminal greeting) we should output the contents of the `UWT_DEV_PASSTHROUGH` variable.

Users can either use `export UWT_DEV_PASSTHROUGH=1` or `ssh.whonix-orig` to circumvent `uwt`. This is not well documented at the moment on the https://www.whonix.org/wiki/Stream_Isolation page.

**Comment by JasonJAyalaP** [comment]
https://phabricator.whonix.org/T73
