### ISSUE TITLE
Better Circumvention User Interface - tor-launcher

### ISSUE THREAD

**Issue by adrelanos** [Whonix/Whonix#167]
TBB uses the tor-launcher add-on, it looks good and makes it simpler to enter bridges. The upcoming version of tor-launcher even support pluggable transports. There is some work done creating a standalone xul application of tor-launcher. Tails devs are planing to use it. Whonix should use it as well. Some older screenshots of tor-launcher can be seen here: [Dev/whonixsetup](https://www.whonix.org/wiki/Dev/whonixsetup). ([Sponsor A](https://www.whonix.org/wiki/Dev/Sponsor/A#Better_Circumvention_User_Interface))

**Comment by adrelanos** [comment]
add environment variable to hide TBB's logo:
https://trac.torproject.org/projects/tor/ticket/14122

**Comment by JasonJAyalaP** [comment]
@adrelanos 
I need you to summarize the current state/next action of this issue (here and/or that forum post).

**Comment by adrelanos** [comment]
This developed into a duplicate of:
https://www.whonix.org/forum/index.php/topic,720.0.html

Or perhaps also a duplicate of #53.

**Comment by adrelanos** [comment]
Migrated:
https://phabricator.whonix.org/T118
