### ISSUE TITLE
install Icedove (Thunderbird) as soon as TorBirdy is in Debian

### ISSUE THREAD

**Issue by adrelanos** [Whonix/Whonix#17]
Done:

* Whonix support in TorBirdy: [\#8029](https://trac.torproject.org/projects/tor/ticket/8029)

Open issues:

*  [\#6018](https://trac.torproject.org/projects/tor/ticket/6018 "task: Add TorBirdy to the torproject.org repository (new)") "Add TorBirdy to the torproject.org repository" or [\#8030](https://trac.torproject.org/projects/tor/ticket/8030 "enhancement: Get TorBirdy into Debian (new)") "Add TorBirdy to the torproject.org repository"

* [Debian Bug report logs - \#699107 ITP: TorBirdy -- configures Mozilla birds for use with Tor](http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=699107) - so hopefully someone is already working on it.

Once it gets shipped by default in Whonix-Workstation, update documentation for next Whonix version: https://www.whonix.org/wiki/E-Mail#Mozilla_Thunderbird_with_TorBirdy

**Comment by JasonJAyalaP** [comment]
https://phabricator.whonix.org/T113
