### ISSUE TITLE
SSL/TLS Mirrors

### ISSUE THREAD

**Issue by fortasse** [Whonix/Whonix#177]
SSL/TLS Mirrors are difficult to implement because of the trust / key issues, but @adrelanos and I have had a couple ideas.

1. Let mirrors use whatever certs/domains they have (hopefully from a "trusted" CA so it doesn't throw alerts to the user), and include their URL in a list. When a user visits the download page, one of those URL is placed into the article using something like [Extension:RandomInclude] (https://www.mediawiki.org/wiki/Extension:RandomInclude). This would be a little cumbersome with caching. Perhaps we could have a static link to something like "whonix.org/download/ssl.php", which would then in turn point to an SSL mirror randomly. 

2. Just make a (new) cert and share it. This is less than ideal, but may be easier than the above.

Ideas are welcome.

**Comment by adrelanos** [comment]
Migrated:
https://phabricator.whonix.org/T145
