### ISSUE TITLE
secure, censor resistant, distributed project metadata

### ISSUE THREAD

**Issue by adrelanos** [Whonix/Whonix#18]
A proposal has been written:
https://www.whonix.org/wiki/Dev/Permanent_Takedown_Attack_Defender

Let's wait until the Whonix repository is up. Perhaps we can archive the same with multiple mirrors of Whonix repository.

**Comment by JasonJAyalaP** [comment]
@adrelanos 
What's next?

**Comment by adrelanos** [comment]
TODO:

Implement the [Permanent Takedown Attack Defender Proposal](https://www.whonix.org/wiki/Dev/Permanent_Takedown_Attack_Defender) into `whonixcheck`. Or better. Upstream the whole thing. Create an emergency news notification mechanism including a Permanent Takedown Attack Defender implementation that Debian would adapt.

**Comment by JasonJAyalaP** [comment]
https://phabricator.whonix.org/T114
