### ISSUE TITLE
clock does not show local time

### ISSUE THREAD

**Issue by adrelanos** [Whonix/Whonix#20]
This most likely requires a Whonix Greeter first (#15).

Some users are confused with the clock being set to UTC. We have to set local time to UTC, because some applications leak it. Can we somehow patch the clock to show a local time zone while leaving system time time in UTC?

It might be possible to configure the clock in the kde task bar. Time zone in kde clock can be changed without root rights and without affecting /etc/localtime, thus the user can have it's clock show what she wants. It looks like this is either configured in /home/user/.kde/share/config/plasma-desktop-appletsrc and/or /home/user/.kde/share/config/ktimezonedrc.

**Comment by JasonJAyalaP** [comment]
https://phabricator.whonix.org/T71
