### ISSUE TITLE
Metalink

### ISSUE THREAD

**Issue by adrelanos** [Whonix/Whonix#21]
As soon as [Metalinks](https://en.wikipedia.org/wiki/Metalink) gets supported by Firefox [(feature request ticket)](https://bugzilla.mozilla.org/show_bug.cgi?id=331979), we should think about providing Whonix downloads as metalinks. It would make file download corruption less likely or even impossible while downloading.

Would only solve halve of the problem: occasionally download image corruption. OpenPGP verification would still be difficult.(Metalinks supports OpenPGP in theory, but there are no implementations of downloaders supporting metalinks also supporting OpenPGP.)

There are also other downloaders supporting Metalink already, including Firefox addons, see [Metalinker website](http://www.metalinker.org/samples.html). Users could be advised to get downthemall from Mozilla Addon. How well gets it reviewed by Mozilla? Would it mess up Tor Browsers fingerprint?

As external gui downloader uget (in Debian, supports metalink) looks quite good, so does cli downloader aria2.

**Comment by JasonJAyalaP** [comment]
2006 feature request still categorized as "new". I don't think this ticket is worth keeping open.

**Comment by adrelanos** [comment]
Sadly, true. Even if someone wanted to contribute, they'd still need to find someone from Mozilla as "mentor". And no one is interested in that.
