### ISSUE TITLE
generic gui tool window icon support

### ISSUE THREAD

**Issue by adrelanos** [Whonix/Whonix#232]
Screenshot:
https://www.whonix.org/w/images/7/71/8.6.2.8-generic-gui-tool.png

window icon: in the left upper corner.

@troubadoour Could you add window icon support to generic gui tool please?

**Comment by JasonJAyalaP** [comment]
@adrelanos  @troubadoour 
Status?

**Comment by adrelanos** [comment]
Still not configurable. Still hard coded.

https://github.com/Whonix/msgcollector/blob/f225fb56b124d2e4156d77c31f20fc7a1024c7f8/usr/lib/msgcollector/generic_gui_message#L21

```
self.setWindowIcon(QtGui.QIcon("/usr/share/icons/anon-icon-pack/whonix.ico"))
```

But more more pretty than the default X one as in the screenshot above. So it's the same for all Whonix apps using `/usr/lib/msgcollector/generic_gui_message`. (That are anon-gw-first-run-notice, open-link-confirmation, tb-updater.) I guess that is acceptable, unless someone thinks those should use a distinct window icon.
