### ISSUE TITLE
Pin check.torproject.org and torproject.org SSL certificates

### ISSUE THREAD

**Issue by adrelanos** [Whonix/Whonix#24]
[\#3555](https://trac.torproject.org/projects/tor/ticket/3555 "enhancement: Pin *.torproject.org's certs in TBB (assigned)") not even Tor Browser does pin the Certificate yet. Mike also says "low priority", where I disagree. Tor Browser [does not pin, but does enforce HSTS for \*.torproject.org in Firefox Beta.](https://trac.torproject.org/projects/tor/ticket/6098#comment:4) the check.torproject.org's SSL certificate. We should do that too for `curl`, since `curl` is used to download Tor Browser and for checking Tor in whonixcheck.

Good news, tpo does offer [SSL fingerprints](https://www.torproject.org/docs/faq.html.en#SSLcertfingerprint).

**Old idea**: `wget`:
* Has a `--ca-certificate <file>`. I haven't found any method to check the fingerprint by command line. [Bug-wget FEATURE-REQUEST Pinning SSL certificates  check SSL fingerprint](https://lists.gnu.org/archive/html/bug-wget/2012-07/msg00008.html) - very unlikely
* Workaround:
```
    ## Create a own local certificate authority and use
    wget --ca-certificate <file\
    openssl s_client -showcerts -connect www.torproject.org:443 >/tmp/x.cert </dev/null
    openssl x509 -in cert.pem -noout -text -pubkey 
```
 * Open question: How to sign a certificate if you have no access to the private key and CSR (certificate signing request)? Therefore created [tor-talk How to pin the SSL certificate for torproject.org?](https://lists.torproject.org/pipermail/tor-talk/2012-July/024701.html). Some suggestions, no suitable solution for Whonix.
[OpenSSL users Sign public key without having CSR or private key?](http://www.mail-archive.com/openssl-users@openssl.org/msg67962.html); [might work](http://www.mail-archive.com/openssl-users@openssl.org/msg67968.html) - didn't test, not sure if it could work.

**New idea**:
Use a hidden service. I also don't think [\#6098](https://trac.torproject.org/projects/tor/ticket/6098 "enhancement: Add a hidden service to check.torproject.org (new)") "[Tor Check]: Add a hidden service to check.torproject.org" has a chance. (A hidden service wouldn't have any SSL cert pining issues and support end-to-end encryption.)

In worst case we have to wait until the problem gets solved in a clean way, i.e. no more need for check.torproject.org because "the client figures out itself", visiting torproject.org trough the hidden service and downloading Tor Browser over secure apt. ([\#5236](https://trac.torproject.org/projects/tor/ticket/5236 "enhancement: Make a deb of the Torbrowser and add to repository (needs_information)") Make a deb of the Torbrowser and add to repository)

***Some progress***:
* [Dev_sslcertpinning](https://www.whonix.org/wiki/Dev/SSL_Certificate_Pinning)
* [SSL](https://www.whonix.org/wiki/SSL)
* started discussion: https://mailman.boum.org/pipermail/tails-dev/2012-September/001694.html
* answer: https://mailman.boum.org/pipermail/tails-dev/2012-October/001874.html
As 

***Plan as in Mai 2013***:
[torbrowser-launcher](https://github.com/micahflee/torbrowser-launcher/) (python) (in Debian `jessie`). This is a good candidate to be added to Whonix by default anyway. (#346) It pins torproject's SSL certificate directly. They ship `torproject.pem` certificate and hopefully keep it updated for all time, which is imho the difficult maintenance part. torbrowser-launcher forum discussion: https://www.whonix.org/forum/index.php/topic,404.0.html

[Dev_sslcertpinning](https://www.whonix.org/wiki/Dev/SSL_Certificate_Pinning) explains how to pin a certificate in `curl`. The required code changes are easy. It remains to be decided if we ship `torproject.pem` ourselves or rely on torbrowser-launcher to keep it updated.

**Comment by JasonJAyalaP** [comment]
@adrelanos I need you to summarize/update the status of this one (for the migration).

**Comment by adrelanos** [comment]
> @adrelanos I need you to summarize/update the status of this one (for the migration).

Will do later.

**Comment by adrelanos** [comment]
As per `curl` changelog (http://curl.haxx.se/changes.html) the `--pinnedpubkey` feature has appeared in `curl` 7.39.0. It's most likely won't be available in `jessie` due to the freeze. This ticket can be implemented in `jessie` + 1.

**Comment by adrelanos** [comment]
Migrated:
https://phabricator.whonix.org/T80
