### ISSUE TITLE
optional non-persistent entry guards

### ISSUE THREAD

**Issue by adrelanos** [Whonix/Whonix#246]
Especially for mobile users this could be interesting. See:

* https://tor.stackexchange.com/questions/698/tracking-user-location-using-entry-guards
(http://www.webcitation.org/6RTwwSWvw)
* https://tor.stackexchange.com/questions/636/is-it-dangerous-to-use-tails-without-persistent-entry-guards (http://www.webcitation.org/6RTwx8bil)

Adding `DataDirectory /var/run/tor` to `/etc/tor/torrc` could do the trick. After every reboot, Tor would use new entry guards. Maybe extra AppArmor rules would be required.

We could start by documenting this issue. Later maybe aid the user switching the setting.

Alternatively, there could be a special mode or setting for not connecting to Tor after Whonix-Gateway started. (At the moment Whonix-Gateway only does not connect to the public Tor network after first boot [to aid "hide Tor from ISP" and bridge users].)

Documentation could explain how to stop the Tor service; wipe Tor's data dir; start Tor service; connect.

**Comment by JasonJAyalaP** [comment]
Safe to close? We can revisit the issue when more research comes up, and when we do the gateway-control-panel.

**Comment by adrelanos** [comment]
We should at least document this for now. Then see how many users ask about it and think about further steps.

**Comment by JasonJAyalaP** [comment]
https://phabricator.whonix.org/T94
