### ISSUE TITLE
Pin check.torproject.org and torproject.org CA SSL certificates

### ISSUE THREAD

**Issue by adrelanos** [Whonix/Whonix#25]
In meanwhile until pinning the SSL certificate directly (#24) gets solved we could also pin the certificate authority.

    curl --verbose --tlsv1 --proto =https --capath /invalid/ --cacert /usr/share/ca-certificates/mozilla/DigiCert_High_Assurance_EV_Root_CA.crt https://check.torproject.org

Maybe we should ask torproject.org how long they want to stick with with that CA.

**Comment by JasonJAyalaP** [comment]
I suspect that our effort is best focused on https://github.com/Whonix/Whonix/issues/24

**Comment by adrelanos** [comment]
This could be easily done. In comparison to #24 which is quite harder. This would could take ~ 2 hours of coding time or so. (Having it fully configurable and disableable.) If it's a good idea maintenance wise (when they change the CA and then lots of users complaining) is another question.

Was open long enough without any arguments... And I need input here.

@HulaHoopWhonix got any arguments here? Is it worth it or wasted effort?
