### ISSUE TITLE
mail OTF for security review

### ISSUE THREAD

**Issue by adrelanos** [Whonix/Whonix#258]
When Whonix 9 has been released, notify OTF and ask for the security review they offered.

**Comment by JasonJAyalaP** [comment]
Can you explain, Patrick?

**Comment by adrelanos** [comment]
1) Read

* https://www.opentechfund.org/labs#redteam
* https://www.opentechfund.org/article/report-how-evaluate-technical-audits-funder
* https://www.opentechfund.org/sites/default/files/attachments/report-public_0.pdf
* https://www.opentechfund.org/sites/default/files/attachments/pre-engagement_checklist.pdf
* https://www.opentechfund.org/sites/default/files/attachments/matrix_-_example.xls

2) Then fill out:

* https://docs.google.com/forms/d/1nrbxhucjKeloQu3eSUkO1rMQ6QwdWNVOQqm-uUZVwjQ/viewform

3) See what they say, answer further stuff.

**Comment by JasonJAyalaP** [comment]
https://phabricator.whonix.org/T62
