### ISSUE TITLE
VirtualBox AHCI

### ISSUE THREAD

**Issue by Neurodrive** [Whonix/Whonix#274]
There is a bug with the SATA AHCI driver that seems to fail under high I/O like when for example the bitcoin client is running, and freezes the computer constantly during its process and then crashing the virtual machine. I recommend switching to the driver on the workstation (the only one under high load) to SAS or IDE. No problem detected using the SAS driver, workstation on for 19+ hours.

This is the bug and there doesn't seem to be a better a fix from VirtualBox
!!Assertion Failed!!
Expression: !ASMAtomicReadU32(&pAhciPort->cTasksActive) || (pAhciReqExcept && ASMAtomicReadU32(&pAhciPort->cTasksActive) == 1)
Location  : /home/vbox/vbox-4.3.14/src/VBox/Devices/Storage/DevAHCI.cpp(5689) bool ahciCancelActiveTasks(PAHCIPort, PAHCIREQ)

**Comment by JasonJAyalaP** [comment]
Closed until we get more info/things to try.

**Comment by adrelanos** [comment]
Any update?

**Comment by CatsDans** [comment]
I have very similar problem - https://www.virtualbox.org/ticket/19429
