### ISSUE TITLE
ram adjusted desktop starter (rads) no more force keep tty1 open

### ISSUE THREAD

**Issue by adrelanos** [Whonix/Whonix#291]
Currently tty1 is set to autologin with user "user", so rads can decide to whether start a graphical login manager or not. When the user types `exit` in that [virtual terminal](http://en.wikipedia.org/wiki/Virtual_console), `/etc/inittab` will cause auto relogin by default.

We can autologin on boot and if the user exits that virtual terminal, we can just show the usual login prompt by using a small script configured in `/etc/inittab`.

```
#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

#set -x

true "$0: whoami: $(whoami)"

lock_file="/var/run/rads_getty_autologin_once"

if [ -f "$lock_file" ]; then
   true "$0: $lock_file exists."
   true "$0: running: exec /sbin/getty 38400 tty1"
   #sleep 10 &
   #wait $!
   exec /sbin/getty 38400 tty1
else
   true "$0: $lock_file does not exist."
   touch "$lock_file"
   true "$0: running: exec /sbin/getty --autologin user 38400 tty1"
   #sleep 10 &
   #wait $!
   exec /sbin/getty --autologin user 38400 tty1
fi
```

**Comment by JasonJAyalaP** [comment]
https://phabricator.whonix.org/T57
