### ISSUE TITLE
Using Tor Consensus on gw to protect against malicious bridges

### ISSUE THREAD

**Issue by HulaHoopWhonix** [Whonix/Whonix#316]
As you brought up on the forum, there is an attack bridges can perform on first-time users. This involves feeding old consensus data (which can be up to a week old).

To counteract this, I propose using the current anondate code on the gateway (not for setting time) but just for the purpose of fetching and comparing consensus data from Directory Authorities, over Tor when bridges are used. Its recommended to let the fetching be done via Tor Stem and the comparison be made with anondate.

The only consensus data used would be verified only. Multiple fetches over different exits are a good idea as a way to guard against malicious exit IPs and to have a consensus on what the consensus should look like.

Ideally this package would be named bridgesanitycheck or bridgehealth.

In the situation that the bridge is malicious, its data would be replaced by the ones agreed on by anondate.

**Comment by JasonJAyalaP** [comment]
migrated to https://phabricator.whonix.org/T56
