### ISSUE TITLE
wizard security vs usability - whonixadvsetup

### ISSUE THREAD

**Issue by adrelanos** [Whonix/Whonix#319]
Reduced usability is also a security problem. On the other hand, educated users don't need many usability features. Those can still be balanced.

Rather than "trash all usability features in favor of security", we could also make a wizard (extend [whonixsetup](https://github.com/Whonix/whonixsetup)). It's already asking about Whonix's repository anyway. And most of Whonix's features are highly configurable anyway (disabling specific [whonixcheck](https://www.whonix.org/wiki/Whonixcheck) functions is already implemented).

> Do you wish to configure further settings related to security vs usability?
>
> * No, just go ahead, use recommended most usable settings.
> * Yes, I am willing to learn more, sacrifice usability for better security.

If user choses no, just keep current defaults

If user chooses, yes, start explaining more stuff in sub menus. Such as

* Explain whonixcheck's Whonix News, and that it may be substituted by regularly reading [Whonix Important Blog](https://www.whonix.org/wiki/Download#Whonix_News_Blogs). User can disable it.
* Explain whonixcheck's Tor Browser update check and that it can be substituted by watching for the small red blinking Tor Browser and how to update in that case.
* Explain whonixcheck's SocksPort / TransPort Test's.
* Explain sdwdate, explain that it can be omitted by manually keeping care of the clock.
* Explain CPFP, what breaks when disabling it, how to substitute it.
* Explain #125 (as soon as implemeneted).

User will be able to enable/disable all one by one and/or enable/disable all at once. (The disable all at once might be interesting for users who already know all that stuff and configure multiple workstations and such who wish to click fast through it.)

**Comment by JasonJAyalaP** [comment]
migrated to https://phabricator.whonix.org/T55
