### ISSUE TITLE
Provide torrent release RSS feed

### ISSUE THREAD

**Issue by fluential** [Whonix/Whonix#337]
Having torrent release RSS feed (vide https://tails.boum.org/torrents/rss/index.rss) would be very useful to automate whonix mirror hosting, providing both HTTP and torrent seeds.

**Comment by fluential** [comment]
Hi I have few issues and I would like to deliver this rather sooner than later so I would appreciate your help here. Do I need to have a whole system built first before running create_torrent? The script itself suggest I should not to as it seeds content from mirrors. Anyway I have the repos as suggested:
root@devdev:~# ls -dl ~/*onix*
drwxr-xr-x 11 root root 4096 Jan 10 11:36 /root/Whonix
drwxr-xr-x 11 root root 4096 Jan 10 11:37 /root/whonix-developer-meta-files

But there are issues related mostly to relative paths when sourcing other files inside create_torrent:
source ../../../help-steps/pre
source ../../../help-steps/variables

Documentation (building from source) did not help much either.
Any suggestions?

**Comment by adrelanos** [comment]
* Please get the source code as `user`, not `root`. (This is because some tools used during the build process must not be run as `root`, they complain.) Instructions assume running the build script from user `user` using `sudo`.
* For create_torrent, `root` is unnecessary.
* The folder structure has been simplified in Whonix 10. Please base your patch/branch on top of master rather than Whonix 9. In Whonix 10, there is no need anymore to manually download `whonix-developer-meta-files`. That folder is located in `~/Whonix/packages/whonix-developer-meta-files`.

> But there are issues related mostly to relative paths when sourcing other files inside create_torrent:

When you get latest master of https://github.com/Whonix/Whonix you won't have any issues with relative paths. After cloning you can get to `~/Whonix/packages/whonix-developer-meta-files` folder. Then edit `./release/create_torrent` or run `./release/create_torrent`.

> Do I need to have a whole system built first before running create_torrent?

No. You just need the files in the correct folder with the correct names. Fake files would do for testing purposes. Or just download the original files and place them there.

```
ls -a1 ~/whonix_binary/
```

```
Whonix-Gateway-9.4.libvirt.xz
Whonix-Gateway-9.4.ova
Whonix-Workstation-9.4.libvirt.xz
Whonix-Workstation-9.4.ova
```

**Comment by adrelanos** [comment]
For testing, you might want to set:
```
export version="9.4"
```
before running `./release/create_torrent` so version / file names match.

**Comment by fluential** [comment]
Superb that makes much more sense, I had master branch as a normal user before and tried do source help-steps/pre manually but this did not work well, I will update soon, thanks for your help.

**Comment by fluential** [comment]
Tryin to run: ./create_torrent --help, I see that I need to do --build then I get:
"You must add --flavor whonix-gateway, --flavor whonix-workstation, --flavor whonix-custom-workstation or --flavor all."
I add --all, but its not supported because you only evaluate like this:
++ '[' all = whonix-gateway ']'
++ '[' all = whonix-workstation ']'
++ '[' all = whonix-custom-workstation ']'
++ '[' all = none ']'

So I try to do that:
./create_torrent --build --flavor whonix-gateway --target virtualbox  --target qcow2
+ error '/home/xxxx/whonix_binary/Whonix-Gateway-10.0.0.2.3-84-gc51850930df68fc2211faaed90ea606bf24b027c.ova not readable!'
./create_torrent: line 50: error: command not found
++ errorhandlergeneral ERR

Ideas? The task is quite simple really, generate something based on that: https://tails.boum.org/torrents/rss/ and replace few strings, maybe something you could do within 5 minutes, less than spend time tying to get my environment "running". Something to consider.

**Comment by adrelanos** [comment]
Use this.
```
export version="9.4"
```
And/or create a fake file with that name in that folder.

Or write an independent script that takes file name or file names as input.

**Comment by fluential** [comment]
Hey, did that, forgot to mention.
I've got some empty files as a placeholder:
ls ~/whonix_binary/
Whonix-Gateway-9.4.libvirt.xz  Whonix-Gateway-9.4.ova  Whonix-Workstation-9.4.libvirt.xz  Whonix-Workstation-9.4.ova

I do:
export version="9.4"
./create_torrent --build --flavor whonix-gateway --target virtualbox --target qcow2
I've got the error mentioned above and some new files inside:
ls ~/whonix_binary/
torrent-9.4  Whonix-Gateway-9.4.libvirt.xz  Whonix-Gateway-9.4.ova  Whonix-Workstation-9.4.libvirt.xz  Whonix-Workstation-9.4.ova

**Comment by adrelanos** [comment]
Try either commenting out these checks and/or better you can create such files using `touch` or so or something like.
```
echo "test file" > "$binary_image_ova_torrent"
```
And so forth.
That way you can trick any file checks and make sure that fake files exist.

**Comment by adrelanos** [comment]
* Whonix has no more torrent releases.
* Whonix has no more download mirror.
* Downloads are possible over https or onion.
