### ISSUE TITLE
anon-ws-disable-stacked-tor: consider replacing rinetd with rlinetd

### ISSUE THREAD

**Issue by adrelanos** [Whonix/Whonix#341]
Has this idea when reading Debian policy. `The configuration file /etc/inetd.conf must not be modified by the package's scripts except via the update-inetd script or the DebianNet.pm Perl module. See their documentation for details on how to add entries.`

-----

package:
https://github.com/Whonix/anon-ws-disable-stacked-tor

-----

Resources:

* https://packages.debian.org/wheezy/rinetd
* vs
* https://packages.debian.org/wheezy/rlinetd

-----

* http://manpages.debian.org/update-inetd
* http://manpages.debian.org/rlinetd.conf

-----

```
apt-cache show rlinetd
```

```
Package: rlinetd
Version: 0.8.2-2
Installed-Size: 304
Maintainer: Robert Luberda <robert@debian.org>
Architecture: i386
Replaces: manpages-pl (<< 20060617-3~)
Provides: inet-superserver
Depends: dpkg (>> 1.9), lsb-base (>= 3.0-6), netbase, psmisc, ucf (>= 3.0015), debconf (>= 0.5) | debconf-2.0, perl, libc6 (>= 2.4), libcap2 (>= 2.10), libwrap0 (>= 7.6-4~)
Recommends: rsyslog | system-log-daemon
Suggests: portmap
Conflicts: inet-superserver, netkit-inetd, xinetd
Description-en: gruesomely over-featured inetd replacement
 rlinetd is designed to replace the BSD inetd. Feature-wise, it is a
 proper superset of the BSD inetd, including rpc support and both udp
 and tcp services. In addition, it supports a number of resource
 limiting features, including full resource limits a la setrlimit(2),
 renicing, chroot and limited per-service instances. To round out the
 features stolen from xinetd, it also supports binding to individual
 interfaces on request, and configurable logging.
Homepage: http://rlinetd.alioth.debian.org/
Description-md5: 0726ce3c088a129c62f12b99d7282689
Tag: implemented-in::c, interface::daemon, network::server, network::service,
 protocol::ipv6, role::program
Section: net
Priority: extra
Filename: pool/main/r/rlinetd/rlinetd_0.8.2-2_i386.deb
Size: 104882
MD5sum: 663d7ed3cc28ed1b3eec57831812e6a3
SHA1: 3c7975183b109b924f285bae523cf83f4fde97c4
SHA256: f712f15b06dba26df139555d58cf4a2ac136cf632d6b383a3b740cb76fe97879
```

-----

```
apt-file list rlinetd
```
```
rlinetd: /etc/init.d/rlinetd
rlinetd: /etc/rlinetd.conf
rlinetd: /usr/lib/i386-linux-gnu/rlinetd/libparse.so
rlinetd: /usr/sbin/inetd2rlinetd
rlinetd: /usr/sbin/rlinetd
rlinetd: /usr/sbin/update-inetd
rlinetd: /usr/share/doc/rlinetd/AUTHORS
rlinetd: /usr/share/doc/rlinetd/BUGS
rlinetd: /usr/share/doc/rlinetd/NEWS.gz
rlinetd: /usr/share/doc/rlinetd/README
rlinetd: /usr/share/doc/rlinetd/README.capabilities
rlinetd: /usr/share/doc/rlinetd/README.inetd
rlinetd: /usr/share/doc/rlinetd/THANKS
rlinetd: /usr/share/doc/rlinetd/THOUGHTS
rlinetd: /usr/share/doc/rlinetd/TODO
rlinetd: /usr/share/doc/rlinetd/changelog.Debian.gz
rlinetd: /usr/share/doc/rlinetd/changelog.gz
rlinetd: /usr/share/doc/rlinetd/copyright
rlinetd: /usr/share/doc/rlinetd/examples/builtins
rlinetd: /usr/share/doc/rlinetd/examples/popper
rlinetd: /usr/share/doc/rlinetd/examples/rlinetd.conf
rlinetd: /usr/share/doc/rlinetd/examples/rpc
rlinetd: /usr/share/doc/rlinetd/examples/simple
rlinetd: /usr/share/lintian/overrides/rlinetd
rlinetd: /usr/share/locale/pl/LC_MESSAGES/rlinetd.mo
rlinetd: /usr/share/man/de/man5/rlinetd.conf.5.gz
rlinetd: /usr/share/man/de/man8/inetd2rlinetd.8.gz
rlinetd: /usr/share/man/de/man8/rlinetd.8.gz
rlinetd: /usr/share/man/man5/rlinetd.conf.5.gz
rlinetd: /usr/share/man/man8/inetd2rlinetd.8.gz
rlinetd: /usr/share/man/man8/rlinetd.8.gz
rlinetd: /usr/share/man/man8/update-inetd.8.gz
rlinetd: /usr/share/man/pl/man5/rlinetd.conf.5.gz
rlinetd: /usr/share/man/pl/man8/inetd2rlinetd.8.gz
rlinetd: /usr/share/man/pl/man8/rlinetd.8.gz
```

-----

rlinetd advantages:

* apparently supports /etc/rlinetd.d
 * (Therefore could make [displacing](http://debathena.mit.edu/config-packages/) /etc/rinetd.conf unnecessary.)
 * (Therefore could lead to more Debian policy conform implementation.)

-----

security:

* https://security-tracker.debian.org/tracker/source-package/rinetd
* vs
* https://security-tracker.debian.org/tracker/source-package/rlinetd

**Comment by adrelanos** [comment]
There is now a real reason to transition away from rinetd. I don't think upstream still cares about rinetd. Never got a reply to the following inquiry.

* https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=796235
* https://www.whonix.org/pipermail/whonix-devel/2015-August/000405.html

What do you think about switching to socat? Then we could also script the port redirection (allowing to easily forward more ports from workstation 127.0.0.1 to the gateway).

(Socat would be useful for better [I2PBOX](https://www.whonix.org/wiki/I2P#Installing_I2P_on_Whonix-Gateway_.28I2PBOX.29) support. - https://www.whonix.org/pipermail/whonix-devel/2016-January/000501.html)

**Comment by HulaHoopWhonix** [comment]
> What do you think about switching to socat? Then we could also script the port redirection (allowing to easily forward more ports from workstation 127.0.0.1 to the gateway).

Good choice. Well supported and widely used.

> (Socat would be useful for better I2PBOX support. - https://www.whonix.org/pipermail/whonix-devel/2016-January/000501.html)

Nice. Diversifies and increases our userbase and does not put load on both networks.

**Comment by adrelanos** [comment]
Migrated to:
https://phabricator.whonix.org/T464
