### ISSUE TITLE
Contributors License Agreement (CLA) / Developer Certificate of Origin (DCO) / Fiduciary Licence Agreement (FLA)

### ISSUE THREAD

**Issue by adrelanos** [Whonix/Whonix#355]
We have https://github.com/Whonix/Whonix/blob/master/CONTRIBUTING.md but formalizing it in form of a CLA, DCO or FLA should be done some day.

**Comment by JasonJAyalaP** [comment]
migrated to https://phabricator.whonix.org/T53
