### ISSUE TITLE
Using cowbuilder for build-steps.d/1200_create-debian-packages?

### ISSUE THREAD

**Issue by adrelanos** [Whonix/Whonix#356]
I am considering to revise `build-steps.d/1200_create-debian-packages`.

Current issues:
* `dpkg-buildpackage` unfortunately does not support a `--outputdir` option ([feature request](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=657401)), so `.deb` packages end up in `../` or in other words in `whonix_source_folder/packages` directory.
* When creating a package, `debhelper` creates temporary files within `whonix_source_folder/packages/$package_name/debian` and as far I know this cannot be prevented either.
* Needless to say, having temporary and binary (`.deb`'s) within Whonix source folder is non-ideal. (Risk of custom builders committing them to `git` or asking when/how/if they can be deleted.)
* Therefore an ugly `[cleanup step](https://github.com/Whonix/Whonix/blob/master/help-steps/cleanup-files)` is required, which risks wiping files which others added in meanwhile.

Current implementation:
* To end up with consistent, non-surprising and comparable results among various builders, `build-steps.d/1200_create-debian-packages` breaks when there are changes uncommitted to `git`. (Unless using `--ignore-uncommited`.)
* Build dependencies are installed on the build system, not in a VM or `chroot`.

[Benchmark: time to build `1` package. We got `~100` packages.]

Current method:
* Benchmark: `make deb-pkg`  (even including lintian): `8s`
* No `chroot` involved.
* Package build dependencies are installed on the host.
* Issues as described above.

`pdebuild` method:
* Benchmark: `pdebuild`: `34s` [+ additional make dist + additional make undist required]
* `chroot` involved.
* Package build dependencies are installed in `chroot`.
* Still autogenerated temporary files within Whonix source folder.

`cowbuilder` method:
* Benchmark: `time sudo -E cowbuilder --build ../sdwdate_1.2-1.dsc`: `24s` [+ additional make dist + additional dpkg-source -b ../ required]; [can be speed up a bit more by installing build dependencies beforehand into `base.tgz`]
* `chroot` involved.
* Package build dependencies are installed in `chroot`.
* Likely no autogenerated temporary / binary files within Whonix source folder.

I think the `cowbuilder` method would have some advantages. No need to install package build dependencies on the host anymore, "cleaner" builds and no more autogenerated temporary files within Whonix source code. Although disadvantage would be, that it would be slower.

(This is only for how to best create all packages in a row using ``build-steps.d/1200_create-debian-packages`. No worries, the `make deb-pkg` method to build individual packages as a builder won't be [can't be] deprecated.)

So I am wondering if I should just go ahead and implement the `cowbuilder` method or if I should add some extra burden to keep compatibility with the current method using an option.

@JasonJAyalaP @troubadoour @HulaHoopWhonix @annonn @kenkes

**Comment by JasonJAyalaP** [comment]
migrated to https://phabricator.whonix.org/T52
