### ISSUE TITLE
list of git tags messed up when running "git tag"

### ISSUE THREAD

**Issue by adrelanos** [Whonix/Whonix#357]
This is a follow up task that results out of:
"better git tag names that reflect stable, testers-only, developers-only" (#276)

Currently when one runs in Whonix/Whonix source folder.

```
git tag
```

They'll get this.

```
[...]
0.5.6
0.6.0
0.6.1
10.0.0.0.1-developers-only
10.0.0.0.2-developers-only
10.0.0.0.3-developers-only
10.0.0.0.4-developers-only
10.0.0.0.5-developers-only
10.0.0.0.6-developers-only
6
6.1
6.2
[...]
8.6.6.9
9
9.1
9.2
9.3
```

Tags names `10.0.0.0.6-developers-only` and similar follow the schema that was implemented in #276.

What's the issue? That `-developers-only` tag ends up somewhere in the middle. Someone who just runs `git tag` might easily miss it and think `9.3` is the latest one.

Any idea what we could do about this?

@JasonJAyalaP

**Comment by JasonJAyalaP** [comment]
Migrated to https://phabricator.whonix.org/T51
