### ISSUE TITLE
Whonix Controller

### ISSUE THREAD

**Issue by adrelanos** [Whonix/Whonix#4]
Whonix's graphical Gateway will require a graphical controller. An alternative to Vidalia, since Vidalia development ceased (was written in C++ and QT) and even The Tor Project currently develops their own limited Vidalia alternative (tor-launcher firefox addon).

It should have the following features.

Whonix-Gateway

* new circuit
* see Tor status (connected, problem, etc.)
* First Time Connection Wizard
 * setting up (private) (obfuscated) bridges
 * setting up flash bridges
* enable TorChat
* enable blog
* enable hidden web
* backup hidden service keys
* view Tor logs
* restart Tor
* run TimeSync
* torify Windows (textual feature)
* torify Other Operating System (textual feature)

Whonix-Workstation

* check if Whoinx-Gateway is reachable
* check Tor status on Whonix-Gateway (requires #3)
* advise to start on Whonix-Gateway, in case it's not running
* get notified about events from Whonix-Gateway, for example "a hidden blog has been enabled on Whonix-Gateway, do you want to continue setup on Whonix-Workstation?"

**Comment by JasonJAyalaP** [comment]
https://phabricator.whonix.org/T89
https://phabricator.whonix.org/T90
