### ISSUE TITLE
Build Debian Packages from Source Code

### ISSUE THREAD

**Issue by adrelanos** [Whonix/Whonix#400]
__Info__:

- For better security, ideally, we wouldn't pull binary packages from Debian's repository during the build of Whonix, but compile all packages from source code.

- sponsor-B would pay a bounty for implementing this. We agreed to try bountysource to get offers.

- For building packages from source code, there is `apt-get source --compile pkg-name`. But for it to work, one has to run `apt-get build-dep pkg-name` beforehand, which downloads binary packages. Is it possible to get to a point, where all packages that are installed/updated, are compiled from source code beforehand? Seems difficult to break the dependency loops. Some more info: https://unix.stackexchange.com/questions/184812/how-to-update-all-debian-packages-from-source-code

- The debootstrap system has a fair number of circular dependencies, and no trivial way to break them. Is it allowed to have a leap of faith, to trust some minimal amount of binary packages for the initial bootstrap. Use local system packages and set of "known-good" binaries to do the initial bootstrap build, then rebuild up from there. (One loop that is non-trivial to break for instance is GCC; which requires an Ada compiler to build the Ada compiler. Another one I can think of is OpenJDK, and ghc.) (modified quote by @NCommander)

- The user should be able to build Debian / Whonix from scratch from source code. (Whonix already got a functional build script, using debootstrap [binary packages] and apt-get [binary packages], that can be used by anyone to build from source.)

- The user should be able to run self rebuilds. For one, `apt-build world` in theory would work nicely for rebuilds from within the running system for us. (Useful to add more compile flags.) Unfortunately, `apt-build` is unmaintained, `world` is broken and written in perl. `apt-build`'s feature set and man page looks very good.

- Do you think you could re-implement all the features of `apt-build` as an apt [download] method, if that makes sense? Aka "apt-build re-implementation in apt". So upstream apt devs get eager to merge and maintain this? So anyone could install any package from Debian sources repository, build and install from source code?

- [rebootstrap](https://wiki.debian.org/HelmutGrohne/rebootstrap) is a nice project, but I don't see how that implements the TODO part.

- [apt-build](https://www.whonix.org/wiki/Dev/apt-build) [...](http://askubuntu.com/questions/29856/how-to-build-all-my-installed-package-from-sources/45257#45257) could help. Unfortunately it is an [orphaned package](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=365427). And might have a [security issue](https://lists.debian.org/debian-security/2015/03/msg00020.html).

- If helpful, this ticket could be split into smaller tasks.

-----

__TODO__:

* add an option to `debootstrap` to install the compile all source packages rather than downloading binary ones
* add an option to or wrapper around `apt-get` to allow installation/upgrade of packages from source code
* It is essential, that patches should be upstreamed to and merged by Debian!
* have an option to modify compile flags per package, so we can for example enable compiling as PIE

-----

Non-Topics:

- Yes, there is really a $ 3000 USD bounty on this ticket.

- We do not want to use EC2 and/or remotely rebuild/maintain the binary archive.

- We don't think we can host our own [binary] repository of the whole Debian package archive anytime soon.

- We are aware of [reproducible builds](https://wiki.debian.org/ReproducibleBuilds). We still want this. Also because we are also after the compiler hardening enhancements.

- apt-get source verification is not the issue here. Verifying the signature of the maintainer may fail indeed, but apt-get source is also always verified against the apt repository singing key. ([See also for explanation](http://askubuntu.com/a/509816/389275).) If you want to discuss this further, let's move this to the [forums](https://www.whonix.org/forum/) or a separate [ticket](http://phabricator.whonix.org/).

- Port to Gentoo. No. (We've been through this (Gentoo) and decided no. (https://github.com/Whonix/Gentoo-Port/issues) Would trade this feature against new issues, including security issues [unsigned files]. [off-topic - if you want to discuss this further, please move it to the Whonix forums])

- Port to other Distributions. No.

- Debian only. Not Ubuntu.

-----

previous / more / archived discussion:
http://www.webcitation.org/6gTIAk6Yj

-----

__Bounty too low?__:

1) Go to https://www.bountysource.com/issues/9115540-build-debian-packages-from-source-code
2) Click on "Developers"
3) Click on "Get Started"
4) Select Status "Bounty too low"
5) Enter your offer and press "Save".

-----

Mirrored from:
https://phabricator.whonix.org/T207

-----

Mirrored to ([restarted the discussion](https://www.whonix.org/blog/debian-packages-from-source-code)):
https://github.com/Whonix/Whonix/issues/400

-----

On bountysource `[*]`:
https://www.bountysource.com/issues/9115540

`[*]` Contains full history discussion. When you are reading on bountysource.com, to save time, I recommend to skip everything up to `I have rewritten the original ticket description.`.

**Comment by afif-elghraoui** [comment]
There is the `apt-build` package. It's been asked about before: http://askubuntu.com/a/45257/214236

I'm not sure if it exactly meets your needs, but it might at least be part of your solution.

**Comment by adrelanos** [comment]
Yes. Good hint, @afif-elghraoui. Unfortunately, it's an [orphaned package](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=365427). And might have a [security issue](https://lists.debian.org/debian-security/2015/03/msg00020.html). Nevertheless, it could indeed be part of the solution. Added some documentation on how to use it here:
https://www.whonix.org/wiki/Dev/apt-build

**Comment by mateli** [comment]
What about building a repository from source that can be installed? Perhaps with check-sums and signed packages so that the systems integrity can be verified?

**Comment by NCommander** [comment]
I am a Debian Developer. and Ubuntu Core Dev, and I've done automated rebuilds of both distributions. I'd be interested in tackling the bounty for this, but I need more information before proceeding to work on it.

1. The debootstrap system has a fair number of circular dependencies, and no trivial way to break them. Is it allowed to use local system packages or a set of "known-good" binaries to do the initial bootstrap build, then rebuild up from there?

One loop that is non-trivial to break for instance is GCC; which requires an Ada compiler to build the Ada compiler. Another one I can think of is OpenJDK, and ghc.

2. Do you want the end-user to build Whonix from scratch, or simply rebuild it yourselves. I can help setup wanna-build/dak/sbuild and train the project team on how to use it; any modified packages could get auto-rebuilt in a snap (so to speak) just like official Debian/Ubuntu packages.

I'll likely have followup questions, but this lets me know where you want to go with this bounty.

**Comment by NCommander** [comment]
Looking at this slightly more:

I'm not sure a patch to rebuild apt-get packages on the fly would be accepted by upstream; builds can (and will) fail if the build environment is unclean; this is why official packages are built in a clean-room so to speak with sbuild (pbuilder is another option used by some people). Writing a patch to invoke sbuild/pbuilder on the fly won't be hard (essentially, apt would have to work out its dependencies list, and use a local repo to grab its brain so to speak); the "easiest" solution would be to implement it as an apt download method which is already nicely abstracted and self-contained, URL goes in, deb comes out

Doing custom CFLAGS should be relatively easy, Ubuntu has hardening-wrapper, and I used the now-defuent lpia port to build the world with -fPIE and a few other things on by default. Modifying hardening-wrapper to read from a config file while in sbuild or similar would be essentially trivial, and work around the age old problem that a million packages have a million ways to specify CFLAGS.

**Comment by adrelanos** [comment]
> The debootstrap system has a fair number of circular dependencies, and no trivial way to break them. Is it allowed to use local system packages or a set of "known-good" binaries to do the initial bootstrap build, then rebuild up from there?

Yes. The sponsor accepts, that we need a leap of faith, to trust some minimal amount of binary packages for initial bootstrap.

> I'm not sure a patch to rebuild apt-get packages on the fly would be accepted by upstream

Can you figure out by talking to upstream on how upstreaming all this could work out? It might likely be possible to agree on a price for discussing this with upstream if it takes non-trivial amount of times and you like to charge for that extra.

> Do you want the end-user to build Whonix from scratch

Yes. Build Whonix from scratch from source.

(Whonix already got a functional build script, using debootstrap [binary packages] and apt-get [binary packages], that can be used by anyone to build from source.)

> Do you want the end-user to build Whonix from scratch, or simply rebuild it yourselves.

Yes, also self rebuilds. For one, `apt-build world` in theory would work nicely for rebuilds from within the running system for us. (Useful to add more compile flags.) Unfortunately, `apt-build` is unmaintained, `world` is broken and written in perl. Anyhow. My point is, that `apt-build`'s feature set and man page looks very good.

Do you think you could re-implement all the features of `apt-build` as an apt [download] method, if that makes sense? Aka "apt-build re-implementation in apt". So upstream apt devs get eager to merge and maintain this? So anyone could install any package from Debian sources repository, build and install from source code?

> I can help setup wanna-build/dak/sbuild and train the project team on how to use it; any modified packages could get auto-rebuilt in a snap (so to speak) just like official Debian/Ubuntu packages.

I don't think we can host our own [binary] repository of the whole Debian package archive anytime soon.

Would this "apt-build re-implementation in apt" require some kind of wanna-build/dak/sbuild/cowbuilder? I figured out how to use cowbuilder during the Whonix build process, it's would be a nice to have, but it's not mandatory and some unrelated issues are in the way (https://phabricator.whonix.org/T52).

**Comment by NCommander** [comment]
I'm going to look at bringing apt-build up to the modern world; it doesn't support multiarch which breaks lots of fun stuff, but it does 90% of the drudge work any modern solution needs. I'm going to work from Ubuntu as a base as I'm most familiar with their base system, but my work should work on any Debian-based distro, and I'll make sure to test it on Whonix.

**Comment by NCommander** [comment]
I've joined the IRC channel to discuss the specifics of this, if you wish to join me.

**Comment by NCommander** [comment]
Ok, I think I have a plan of attack, and after reading through the Whonix documentation to see how current builds are done, I think I can break things down to the following steps:

1. Implement the rsbuild tool

rsbuild (short for recursive sbuild) takes a given binary package, determines it dependencies, source dependencies, and recurses through those to build a master list of dependencies. It then rebuilds each one in turn, filling in missing dependencies from Debian if needed, and uploading them to a local archive. To use Gentoo terminology this can generate a "stage1" set of debs which can then be used to rebuild itself. The end-result of running rsbuild is it can generate all the packages required for debootstrap, their dependencies, and (most importantly) their build-dependencies, leaving us with an easily rebuildable base.  Each package is built in a clean-room similiar to the official Debian and Ubuntu packages, using chroots, or lxc containers (not sure if sbuild ever landed the patch for these).

rsbuild can then rebuild the root using the stage1 binaries to form stage2, which is build against itself. For instance, if Whonix implements a patch to GCC that has -fuber-secure, stage2 would be built against that GCC vs. Debian's GCC. hardening-wrapper can be introduced at this stage to enable abitirary C/CPPFLAGS.

The upshot is the core system can be rebuilt on demand; the binNMU feature can be used to genereate debs that can auto-upgrade via apt-get dist-upgrade for in-place upgrades.

2. Create apt-transport-rsbuild

This is a wrapper that sits on apt. When a user does "apt-get install foo", it will check the local package repo to see if foo has been built, and if not, build foo, its dependencies, build-dependencies etc. We'll have to do some special handling of package loops here to make life "saner" so to speak, but it shouldn't be too difficult (essentially handle special casing for when X depends on X to build).

This basically allows rebuilding everything on the fly by doing rsbuild to generate the debootstrap debs, then apt-get install whonix-desktop. Basically, the user experience would be identical to using apt-get normally, except everything rebuilds on the fly transparently. Obviously, if a user wants to use binary packages, they could do so by specifying normal deb lines in /etc/apt/sources.list. Since this sits below libapt so to speak, GUI tools and such should "just work".

My initial goal is to get the initial debootstrap bit working since we can freely pull against the local system to solve loops and that makes coding a *LOT* simpler, as well as getting (more or less) instant payoff.

**Comment by adrelanos** [comment]
As explained on IRC, upstreaming this is essential, because after you contributed this, we don't have anyone who could maintain it. Therefore, do you think you can find appropriate Debian packages who's maintainers would be eager to include this functionality?

For example, eventually the rsbuild functionality would be a nice addition to dpkg, dpkg-query or apt-get?

**Comment by dekkers** [comment]
You're saying that you want to rebuild all Debian packages from source for security reasons. Am I right that the reason that you want to do this is that you want to be sure that the binary packages you distribute are really build from the distributed source packages and no malicious code is inserted?

If so, then do you know of Debian's project to create reproducible builds: https://wiki.debian.org/ReproducibleBuilds? I think it would be more useful to spend resources on getting all Debian packages to build reproducible with the standard Debian toolchain and making it possible for people to easily rebuild and verify that the packages are indeed built from the correct source.

**Comment by adrelanos** [comment]
> You're saying that you want to rebuild all Debian packages from source for security reasons. Am I right that the reason that you want to do this is that you want to be sure that the binary packages you distribute are really build from the distributed source packages and no malicious code is inserted?

Not exclusively. It's also about additional hardening compile flags.

**Comment by dekkers** [comment]
> Not exclusively. It's also about additional hardening compile flags.

If you want to recompile all packages with different compile flags then you can do that with the standard Debian buildd software (https://www.debian.org/devel/buildd/) and a dpkg-buildflags that is configured with different compile flags as far as I know. Would that work for whonix? I've also seen other people talking about doing similar things and one of the proposals was a Debian amd64-hardening (sub)architecture: http://balintreczey.hu/blog/proposing-amd64-hardened-architecture-for-debian/.

**Comment by adrelanos** [comment]
> Would that work for whonix?

I don't know. You tell me. Looks like a lot work. Our build system doesn't assume ssh/mail based builds or so. Looks more like a server/client implementation, where maintainers upload source packages to a server which then compiles them and provides binary packages in the repository. Whonix is too small to maintain that kind of infrastructure. An "apt-build alike" approach that seems more "client-like" seems more doable. (apt-build has issues, that have been discussed above.)

> one of the proposals was a Debian amd64-hardening (sub)architecture: http://balintreczey.hu/blog/proposing-amd64-hardened-architecture-for-debian/.

Awesome stuff. If it was done in Debian, that would be ideal, because then Whonix would just use that architecture and wouldn't need any extra delta, extra complexity. Just got a reply about the status of that project:
https://www.whonix.org/pipermail/whonix-devel/2015-April/000336.html

**Comment by NCommander** [comment]
Bah, I got sidetracked by real life. In all honesty, a single EC2 instance could probably drive through the entire Whonix distro in about a week; less, depending on how many nodes you throw at it; Ubuntu has used EC2 to rebuild their archive, and I've done it locally; it takes about 30 GiB of disk for all the binaries. Individual package build requirements vary, but I don't remember any needing more than 8-10 GiB *at* most including intermediate files (OOo being a key offender here). Excluding the arch:all packages (which are either Java or scripts), that number drops to about 20 GiB. 

Setting up archive software (dak, reporepro, or mini-dak) then using a syncing script to mass import Debian and Whonix source packages would allow you to have complete and total control over the binaries distributed by whonix.

My understanding of the scope of the project was to allow end-users to rebuild Whonix on 127.0.0.1, which as I listed before is somewhat complicated (I made some more progress on rsbuild, but my day job got in the way of future process).

dekkers: dpkg-buildpackage supports setting the C/CXXFLAGS ENV variables; not all packages respect this, or handle them in a sane way. It's the same reason the -j option isn't used in official builds (nor will it likely for the forseable future). That's why Ubuntu created hardening wrapper, which (ab)uses alternates to replace GCC with a shell script that passes the correct options every time.

**Comment by adrelanos** [comment]
I don't think we want to use EC2 and/or remotely rebuild/maintain the binary archive.

> My understanding of the scope of the project was to allow end-users to rebuild Whonix on 127.0.0.1, which as I listed before is somewhat complicated (I made some more progress on rsbuild, but my day job got in the way of future process).

Yes. Thanks for the update!

**Comment by noflag** [comment]
Whoa, someone posted a $3000 bounty for this?

**Comment by adrelanos** [comment]
Yes, it's real.

**Comment by T145** [comment]
What are all of the apt repositories that are required for Whonix? In other words, if I were to run `apt-get install package`, what would I put for `package`?

**Comment by adrelanos** [comment]
> What are all of the apt repositories that are required for Whonix? In other words, if I were to run `apt-get` `install package`, what would I put for `package`?

Off-topic. Please ask in the usual places https://www.whonix.org/forum/ or https://phabricator.whonix.org.

**Comment by tasaif** [comment]
You mean you want Gentoo, but with Ubuntu packages?

**Comment by Shnatsel** [comment]
There's a bit of a security problem with building packages from source under Debian - namely, verifying the source code signatures. 

Debian archive (and Ubuntu archive as well) keeps the signatures of the original maintainers on the source code and does not add an archive signature to source code packages like it does to binary packages. So for verifying the signatures you always need the up-to-date keyring with each and every maintainer key and no extra keys. Maintenance of such a keyring has proven problematic in the past for my setups - it would create too many false positives for signature spoofing and require manual intervention. 

And this is exactly the problem with apt-build: it just doesn't do any source code verification because, given Debian archive, it's simply too tedious.

I reckon a continuous reproducible rebuild of the archive with verification and not rebuild on the client would be a better idea; after all, maintaining it in a single central place would be easier than trying to shove that maintenance to the user. Alternatively, you should get Debian to sign the source code accepted into the archive and get signatures that you can reasonably verify on the client without risking all sorts of race conditions.

**Comment by adrelanos** [comment]
@tasaif: If you want to discuss this further, let's move this to the [forums](https://www.whonix.org/forum/) or a separate [ticket](http://phabricator.whonix.org/).

@Shnatsel: apt-get source verification is not the issue here. Verifying the signature of the maintainer may fail indeed, but apt-get source is also always verified against the apt repository singing key. ([See also for explaination](http://askubuntu.com/a/509816/389275).) If you want to discuss this further, let's move this to the [forums](https://www.whonix.org/forum/) or a separate [ticket](http://phabricator.whonix.org/).

**Comment by shawnl** [comment]
Guys. Debian's Multiarch bootstrap has to deal with these problems all the time. What you have to set up is a buildd.

**Comment by matyapiro31** [comment]
@adrelanos how do you solve build dependency loop?
e.g. you need gcc to build gcc.
Packages that depends on themselves while building should be installed from binary.

**Comment by shawnl** [comment]
> how do you solve build dependency loop?

staged builds. Seriously, Debian is way ahead of you (and Gentoo is ahead of Debian for bootstraping), just join forces #rebootstrap on irc.oftc.net

https://wiki.debian.org/HelmutGrohne/rebootstrap

**Comment by matyapiro31** [comment]
@adrelanos 
I found the way.
`apt-rdepneds` command is the best way.
It can show build dependency recursively.

**Comment by matyapiro31** [comment]
The command `apt-rdepends` doesn't have an option to exclude specified package or section.
I will make apt-emerge (command like gentoo emerge) soon.
Is this worth getting bounties?

**Comment by adrelanos** [comment]
Did you read the whole thread before answering?

> @adrelanos how do you solve build dependency loop?

1) I don't. I am not the one implementing this ticket. Someone else hopefully will. That's what the bounty is for.
2) It has already been stated here:
https://github.com/Whonix/Whonix/issues/400#issuecomment-87454388

>>    how do you solve build dependency loop?

> staged builds. Seriously, Debian is way ahead of you (and Gentoo is ahead of Debian for bootstraping), just join forces #rebootstrap on irc.oftc.net

> https://wiki.debian.org/HelmutGrohne/rebootstrap

That's a nice project, but I don't see how that implements the TODO part listed in the original ticket description.

> I will make apt-emerge (command like gentoo emerge) soon.
> Is this worth getting bounties?

Depends. Likely, if it does what I think. Please describe what it's going to do, how it will be different from apt-build. Implemented in which language? Upstreamed to Debian? Will it be like apt-build, but in an updated, secure, working and maintained way? (https://github.com/Whonix/Whonix/issues/400#issuecomment-83129220)

**Comment by matyapiro31** [comment]
@adrelanos apt-rdepends is written in Perl same as apt-build. apt-rdepends only analyze dependence or build dependence recursively. 
apt-rdepends is maintained in Debian.
I think apt-build is the easiest way to build, but the problem is not maintained.
Security problem can be solved by gpg signing by the user themselves.
To use debootstrap is too slow, I recommend docker.
My idea is argueing data from apt-rdepeds,let apt-build build package in docker.

**Comment by oz123** [comment]
May I suggest an outrageous idea? Instead of building this feature you should seriously consider making whonix based on either pkgsrc or portage from gentoo. The both offer much better control on how you build packages.

**Comment by adrelanos** [comment]
We've been through this (Gentoo) and decided no. (https://github.com/Whonix/Gentoo-Port/issues) Would trade this feature against new issues, including security issues [unsigned files]. [off-topic - if you want to discuss this further, please move it to the Whonix forums]

**Comment by dupingping** [comment]
It's only for debian? or ubuntu is possible?

**Comment by adrelanos** [comment]
DuPingPing:
> It's only for debian? or ubuntu is possible?

Debian only.

**Comment by iHateInventNames** [comment]
Does someone work on this?

**Comment by richard-fairthorne** [comment]
**In response to the initial ticket:**

Q: Is it possible to get to a point, where all packages that are installed/updated, are compiled from source code beforehand?

A: Yes. Download pre-compiled binaries.

**If, as I suspect, you really meant:**

Q: Is it possible to get to a point, where all packages that are installed/updated, are compiled from source at build time?

A: No. The answer is no. It is not possible.

A _good compromise_ might be to calculate a set of binary packages that can be used as a bootstrap, and compile the rest.

If you are interested in this, let me know. I'd be interested in working on it.

**Comment by adrelanos** [comment]
> Does someone work on this?

Given the lack of responded of people trying to work on this earlier, I think it's safe to assume no one is working on this at the moment.

> In response to the initial ticket:
> ...
> If, as I suspect, you really meant:
> ...
> If you are interested in this, let me know. I'd be interested in working on it.

I am afraid you'll have to read the whole ticket to figure out what that is. At the size of this ticket, I recognize that is a task in itself. I'll be summarizing and restarting the whole discussion.

**Comment by adrelanos** [comment]
I lock the conversation for now and will reopen in a few hours when I am done summarizing this ticket.

**Comment by adrelanos** [comment]
http://www.webcitation.org/6gTIAk6Yj

**Comment by adrelanos** [comment]
I have rewritten the original ticket description.

**Comment by Arthur2e5** [comment]
> And [apt-build] might have a security issue.

Seems to be fixed (well, silented) with https://anonscm.debian.org/cgit/collab-maint/apt-build.git/commit/?id=98c035ae03b4da2ad1e92586151ad7638918e758. It sounds pointless to me to care about signature/trust for a local package that you have just built seconds ago, so I guess this `trusted=` override is the right solution.

**Comment by iHateInventNames** [comment]
@Arthur2e5, doesn't look like it solves dependencies compilation?

**Comment by burner1024** [comment]
Could you clarify how exactly does this provide "better security"? Specifically, what threats is it supposed to protect from?

**Comment by adrelanos** [comment]
- More security compilation flags.
- Alternative to Debian reproducible project. [...]

**Comment by burner1024** [comment]
So... no actual threat model?

I'm considering to take on this, but I'm not yet convinced whether it's a good idea. You can't seriously expect users to search the internets for security compilation flags in relevant software, enabling them, recompliling software, etc. People who can do all that won't need Whonix to secure their communication.

Not sure, is this sort of discussion better be had here or over at bountysource?

**Comment by adrelanos** [comment]
Ilya Ivanov:
> So... no actual threat model?

Debian reproducible project is a long way to go for reproducible
packages. Reproducible iso dvd images and raw disk images are even more
far away. And even if Debian was all reproducible, it needs lots of
auxiliary stuff, such as independent rebuilds on distributed computers
to check if what the Debian web site claims matches what others builds
and anonymous random sample downloads for verification of what Debian
packages offers for download really match the checksum and perhaps other
stuff.

In meanwhile if users can build Whonix from source code and compile as
many packages from source code themselves (while a small binary
bootstrap package was would still be required), the chance of backdoors
can be reduced to fewer packages.

> You can't seriously expect users to search the
> internets for security compilation flags in relevant software,
> enabling them, recompliling software, etc.

We don't expect this. This ticket is only the first step. Enabling
compilation hardening options for users by default would be the next
step in the evolution. For now the related TODO item is just "have an
option to modify compile flags per package, so we can for example enable
compiling as PIE" which is no the end of later improvements.

> Not sure, is this sort of discussion better be had here or over at
> bountysource?

Github / bountysource comments are just mirrored AFAIK. Anyhow. I am not
comfortable with the discussion here so or so. It extends the thread
length and may deter people who might be skilled to implement it because
the discussion is so lengthy even though it may just be a theoretic debate.

Whonix forums would be better for prolonged discussion if this is worth
going for.

https://forums.whonix.org/t/bounty-3-000-usd-build-debian-packages-from-source-code

**Comment by morriswinkler** [comment]
Is this still up for a go. I would suggest a common solution that is used in the chicken egg problem. 

 The basic feature set as far is I understood. Please correct me.

* rebuild either all packages or some selected packages from  the debian source repro
* do it inside a buildroot, that is debootstraped from only sources, no binary packages allowed
* save the packages to a debian repository structure adding Packages, Release and Release.gpg ( this will allow to either replace packages of a running system or bootsrap a new one )
* manage dpkg-buildflags 

This will be slow, my approach would be threaded, I would also not implement it as a apt tool directly, rather I would build a working version and port it to c++ in a second step later.  


My steps would be:

* building a dependency solver using Sources.gz and Packages.gz files as input 
* validating downloads with Checksums-Sha256 and gpg signatures
* building a bootstrapped fakeroot that is completely compiled from source 
* create a threaded buildbot that stashes deb packags into a local repro
* taking care of either replacing a selection or all installed packages
* intorduce dpkg-buildflags into the process

**Comment by adrelanos** [comment]
No longer current.
