### ISSUE TITLE
Progress bar window title & message empty in gateway

### ISSUE THREAD

**Issue by adamroderick** [Whonix/Whonix#401]
When resuming a Whonix-Gateway VM in virtual box after 2 days of non use, running Timesync and WhonixCheck it shows a message showing the following text for the title and message:

Title: 'Variable progressbartitlex does not exist.  Please re...'
Message: 'Progress bar message is empty, please report this Whonix bug!'

This only occurred in the gateway, the workstation produced the normal title and message.

![file may 29 12 48 59 pm](https://cloud.githubusercontent.com/assets/9330981/7891388/23901648-0601-11e5-9b78-cc78739ebe8d.jpeg)

Edit.  This is with version 1.9-1 of Whonix-Gateway, the issue resolved after restart.  All packages were update updated 5.27.15

**Comment by adrelanos** [comment]
By resume you mean using VirtualBox's snapshot and/or pause feature or just idle?

It has been reworked in Whonix 11. Please test if you can.

Testers Wanted! Whonix 11 ( 11.0.0.2.3 ):
https://www.whonix.org/blog/whonix-11-testers-wanted

**Comment by adrelanos** [comment]
User disappeared.
