### ISSUE TITLE
"Please report this bug"

### ISSUE THREAD

**Issue by e5f3c2ea895af0f27667** [Whonix/Whonix#411]
My Tor Browser crashed for some reason and this box showed up:

> ##################################################### ##                
torbrowser script bug. ## No panic. Nothing is broken. Just some rare condition ## has been hit. Try again later. There is likely a ## solution for this problem. Please see the Whonix News, ## Whonix User Help Forum and Whonix Documentation. ## https://www.whonix.org/wiki/Tor_Browser ## Please report this bug! ## ## BASH_COMMAND: "$tb_browser_folder/Browser/start-tor-browser" --allow-remote "$@" ## exit_code: 139 ## ## output: /usr/lib/msgcollector/msgcollector ## output_opts: --icon /usr/share/icons/anon-icon-pack/tbupdate.ico --parentpid 6934 --identifier torbrowser --parenttty none --whoami user ## progressbaridx: ## ## Experts only: ## bash -x torbrowser                                          
> ##################################################### ##

(I'm using whonix-ws on Qubes OS 3.2)

**Comment by adrelanos** [comment]
A minor tb-updater bug fixed in Whonix 14.

What really is happening that Tor Browser exited with a non-zero exit
code. The same would happen if you manually started it.

cd .tb/tor-browser/

./start-tor-browser.desktop

echo $?
