### ISSUE TITLE
Website's down!

### ISSUE THREAD

**Issue by KuzMaxOriginal** [Whonix/Whonix#412]
Hello! I just wanted to download the latest version of whonix, but now i'm trying to access your website (whonix.org) and I get error - "Unable to connect". However, I checked different browsers, proxies and even through TOR I cant get any page of your website. So I have the reason to tell you, guys, that your website's down :)

**Comment by fortasse** [comment]
You're right, it is! We're currently working on getting everything back online. Sorry for the trouble!

**Comment by KuzMaxOriginal** [comment]
Fortasse, thanks for your quick reply! Can you tell me some other ways to download Whonix?

**Comment by kalle999** [comment]
This is not quite correct.
http://whonix.thecthulhu.com/

**Comment by adrelanos** [comment]
https://www.whonix.org is back online.

**Comment by tranthucbkv** [comment]
the webpage is down again

**Comment by adrelanos** [comment]
Works for me.
