### ISSUE TITLE
Make tor configuration configurable globally (TemplateVM level)

### ISSUE THREAD

**Issue by t4777sd** [Whonix/Whonix#422]
Currently tor can only be configured for a specific App VM via the file /usr/local/etc/torrc.d/50_user.conf

It would be good to have a file that is guaranteed to not be overwritten in upgrades that can be configured at the templateVM level. 

There exists a directory /etc/torrc.d/ where the file /etc/torrc.d/95_whonix.conf is linked. Unfortunately, adding new files to this directory does not cause them to be parsed. Every config file should be parsed in that directory (that is normally how config directories work) or else a specific file should be included such as %include /etc/torrc.d/50_user.conf that will guarantee not be overwritten.

The advantage of this is that each gateway instance can share some global config.

**Comment by adrelanos** [comment]
discussed here already:

https://github.com/Whonix/anon-gw-anonymizer-config/pull/11
