### ISSUE TITLE
Unable to verify latest code release: "tag 14.0.1.4.4-stable not found"

### ISSUE THREAD

**Issue by jmliz** [Whonix/Whonix#427]
I came into this issue while following Whonix code verification documentation here:

https://www.whonix.org/wiki/Dev/Get_Whonix_Source_Code

The documentation instructs users to verify the latest code release tagged `14.0.1.4.4-stable`, which matches with the Downloads page version, but the tag `14.0.1.4.4-stable` for the latest release doesn't exist on this repository. I cloned following the instructions:

```
git clone --jobs=4 --recursive https://github.com/Whonix/Whonix
cd ./Whonix && git verify-tag 14.0.1.4.4-stable
```

gives the following error:

```
error: tag '14.0.1.4.4-stable' not found.
```

I am also unable to find the tag using github tag search.

That issue is keeping me for verifying the latest release code. If another verification method exists let me know.

**Comment by adrelanos** [comment]
Fixed. Thanks.

**Comment by adrelanos** [comment]
Btw if you're interested in development: Then git master would be
better. All git commits are signed, too. And git master was just
recently switched to buster.

https://forums.whonix.org/t/port-whonix-from-debian-stretch-to-debian-buster/7101/2

**Comment by jmliz** [comment]
Thanks! I was just trying to build the image.
