### ISSUE TITLE
last_failed_bash_command: $apt_get_update_wrapper_source_path_full ${APTGETOPT[@]} -o Dir::Etc::sourcelist="$whonix_build_sources_list_primary" -o Dir::Etc::sourceparts="-" update

### ISSUE THREAD

**Issue by el-cpu** [Whonix/Whonix#435]
Hello. Trying to build Whonix from source with this instruction:

https://www.whonix.org/wiki/Dev/Build_Documentation/15_full

I tried both stable and developers-only different versions and get the same error all the time - now I post here all the ###### error part of the output that I get after build command:

last_failed_bash_command: $apt_get_update_wrapper_source_path_full ${APTGETOPT[@]} -o Dir::Etc::sourcelist="$whonix_build_sources_list_primary" -o Dir::Etc::sourceparts="-" update
############################################################
'
++ unset error_reason
++ '[' ERR = INT ']'
++ '[' ERR = TERM ']'
++ '[' ERR = ERR ']'
++ '[' '!' 1 = 0 ']'
++ '[' '' = '' ']'
++ whonix_build_auto_retry_counter=1
++ '[' -n 1 ']'
++ '[' -n 5 ']'
++ '[' '$apt_get_update_wrapper_source_path_full' = error_ ']'
++ '[' 1 -gt 1 ']'
++ true 'INFO: Auto retry attempt number: 1. Max retry attempts: 1 (--retry-max). Auto retry... '
++ whonix_build_auto_retry_counter=2
++ '[' '!' 5 = 0 ']'
++ true 'INFO: Waiting (--retry-wait) 5 seconds before auto retry... '
++ wait 4424
++ sleep 5
++ ignore_error=true
++ error_handler_do_retry=true
++ errorhandlerretry
++ '[' '!' '' = '' ']'
++ true 'INFO: Skipping whonix_build_dispatch_before_retry (--retry-before), because empty, ok.'
++ true 'INFO: Retrying last_failed_bash_command...: $apt_get_update_wrapper_source_path_full ${APTGETOPT[@]} -o Dir::Etc::sourcelist="$whonix_build_sources_list_primary" -o Dir::Etc::sourceparts="-" update '
++ retry_last_failed_bash_command_exit_code=0
++ eval '$apt_get_update_wrapper_source_path_full' -o 'Dir::Etc::sourcelist="$whonix_build_sources_list_primary"' -o 'Dir::Etc::sourceparts="-"' update
+++ /home/candra/Whonix/packages/security-misc//usr/lib/security-misc/apt-get-wrapper -o Dir::Etc::sourcelist=/home/candra/Whonix/build_sources/debian_stable_current_clearnet.list -o Dir::Etc::sourceparts=- update
/home/candra/Whonix/packages/security-misc//usr/lib/security-misc/apt-get-wrapper: line 28: python3.7: command not found
Err:1 http://HTTPS///deb.debian.org/debian-security buster/updates InRelease
  Could not resolve 'HTTPS'
Err:2 http://HTTPS///deb.debian.org/debian buster InRelease
  Could not resolve 'HTTPS'
Reading package lists...
W: Failed to fetch http://HTTPS///deb.debian.org/debian-security/dists/buster/updates/InRelease  Could not resolve 'HTTPS'
W: Failed to fetch http://HTTPS///deb.debian.org/debian/dists/buster/InRelease  Could not resolve 'HTTPS'
W: Some index files failed to download. They have been ignored, or old ones used instead.
++ retry_last_failed_bash_command_exit_code=127
++ true
++ '[' 127 = 0 ']'
++ true 'INFO: Retry failed. exit code of last_failed_bash_command: 127 '
++ last_failed_exit_code=127
++ last_failed_bash_command='$apt_get_update_wrapper_source_path_full ${APTGETOPT[@]} -o Dir::Etc::sourcelist="$whonix_build_sources_list_primary" -o Dir::Etc::sourceparts="-" update'
++ '[' '!' '' = '' ']'
++ true 'INFO: Skipping whonix_build_dispatch_after_retry (--retry-after), because empty, ok.'
++ '[' 127 = 0 ']'
++ errorhandlerprocessshared 'NONE_(called_by_errorhandlerretry)'
++ last_script=././build-steps.d/1120_prepare-build-machine
++ trap_signal_type_previous=ERR
++ '[' ERR = '' ']'
++ trap_signal_type_last='NONE_(called_by_errorhandlerretry)'
++ whonix_build_error_counter=2
+++ benchmarktimeend 1595277412
++++ date +%s
+++ benchmarktimeend=1595277428
+++ benchmark_took_seconds=16
++++ convertsecs 16
++++ local h m s
++++ (( h=16/3600 ))
++++ true
++++ (( m=(16%3600)/60 ))
++++ true
++++ (( s=16%60 ))
++++ printf '%02d:%02d:%02d\n' 0 0 16
+++ echo 00:00:16
++ benchmark_took_time=00:00:16
++ local first
++ read -r first _
++ processbacktracefunction
++ true 'INFO: BEGIN: processbacktracefunction'
++ '[' -o xtrace ']'
++ set +x
++ true 'INFO: END  : processbacktracefunction'
++ functiontracefunction
++ true 'INFO: BEGIN: functiontracefunction'
++ '[' -o xtrace ']'
++ set +x
++ true 'INFO: END  : functiontracefunction'
++ output_cmd_set
++ '[' -o xtrace ']'
++ output_cmd=true
++ true '
############################################################
ERROR in ././build-steps.d/1120_prepare-build-machine detected!

dist_build_version: 15.0.1.3.8
whonix_build_error_counter: 2
benchmark: 00:00:16
last_failed_exit_code: 127
trap_signal_type_previous: ERR
trap_signal_type_last    : NONE_(called_by_errorhandlerretry)

process_backtrace_result:
1: : init
2: : /usr/bin/mate-terminal -x /bin/sh -c '\''/home/candra/Desktop/dns.sh'\'' 
3: : bash 
4: : sudo /home/candra/Whonix/whonix_build --flavor whonix-gateway-xfce --target qcow2 --repo true --build 
5: : /bin/bash /home/candra/Whonix/whonix_build --flavor whonix-gateway-xfce --target qcow2 --repo true --build 
6: : /bin/bash ././build-steps.d/1120_prepare-build-machine 

function_trace_result:
main (line number: 245)
main (line number: 242)
build_machine_setup (line number: 85)
errorhandlergeneral (line number: 367)
errorhandlerprocessshared (line number: 251)
errorhandlerretry (line number: 178)
errorhandlerprocessshared (line number: 196)
errorhandlerprocessshared (line number: 196)
errorhandlergeneral (line number: 367)
build_machine_setup (line number: 85)
main (line number: 242)
main (line number: 245)

last_failed_bash_command: $apt_get_update_wrapper_source_path_full ${APTGETOPT[@]} -o Dir::Etc::sourcelist="$whonix_build_sources_list_primary" -o Dir::Etc::sourceparts="-" update
############################################################

And here is the end of the output:

'ERROR in ././build-steps.d/1120_prepare-build-machine detected!

Please have a look above (the block within ###...).

 - Please enter c and press enter to ignore the error and continue building. (Recommended against!)
 - Please press r and enter to retry.
 - Please press s and enter to open an chroot interactive shell.
 - Please press a and enter to abort.'
++ read -p 'Answer? ' answer
Answer? 

I checked this discussion: http://forums.dds6qkxpwdeubwucdiaord2xgbbeyds25rbsgr73tbfpqpt4a6vjwsyd.tor2web.to/t/building-whonix-from-source-errors/9528#! 

And made sure I have apt-cacher-ng version 3.1 and tried this comand before building:

git checkout --recurse-submodules 15.0.1.3.8-developers-only

Ubuntu 18.04 (modified)

Please help. Thank you.

**Comment by adrelanos** [comment]
As per build documentation:

> You need to build on Debian buster, such as Whonix-Workstation ™ 15 or a Debian buster VM.

Building on Ubuntu is untested and might not work.

You need python3.7 installed. Try this:

    sudo apt update
    sudo apt install python3.7-minimal
