### ISSUE TITLE
Add Wasabi Bitcoin wallet

### ISSUE THREAD

**Issue by ratpoison4** [Whonix/Whonix#436]
[Wasabi Wallet](https://wasabiwallet.io/) is lite wallet focused on privacy. It has coin join function allowing to mix coins with other users of the Wallet. It uses Tor by default to anonymize the user. It uses BIP-157 block filters to protect user's list of addresses. In Electrum servers see the list of user's addresses, so if one address is deanonymized, the whole wallet is. In wasabi you see if a coin was mixed (anonymized) and who may know about your ownership of it.

I think the Wallet is worth being added to Whonix workstation and also to Whonix documentation to this section: https://www.whonix.org/wiki/Bitcoin#Anonymizing_Existing_Bitcoins as it is a non-custodial and cheap way of mixing better in my opinion than washing through exchanges and/or Monero.

**Comment by adrelanos** [comment]
We don't use this issue tracker. See:
https://www.whonix.org/wiki/Reporting_Bugs

**Comment by adrelanos** [comment]
Will answer here:

https://phabricator.whonix.org/T1000

**Comment by ratpoison4** [comment]
Nice issue number :-)

![image](https://user-images.githubusercontent.com/53399252/91709010-22ae9800-eb50-11ea-90a7-cab43cbbdeaa.png)
