### ISSUE TITLE
perform scaning with Nmap trough whonix gateway

### ISSUE THREAD

**Issue by ouledzmitli** [Whonix/Whonix#437]
hello , i want to know if we can perfom an anonymous scan with Nmap trough whonix gateway , i searched in google i  found that it is impossible because Nmap will shows many open false ports , so please any suggestion about this issue

**Comment by TNTBOMBOM** [comment]
https://www.whonix.org/wiki/Unsupported

**Comment by adrelanos** [comment]
https://forums.whonix.org/t/allow-discussion-anonymous-pentesting-in-whonix-forums/554

**Comment by adrelanos** [comment]
https://www.whonix.org/wiki/Declined
