### ISSUE TITLE
Whonix live mode boot fail 

### ISSUE THREAD

**Issue by prorounak2005** [Whonix/Whonix#442]
![Screenshot from 2021-09-16 10-04-10](https://user-images.githubusercontent.com/69617708/133550024-284c83e8-4911-4874-84d8-5204c35a398d.png)

**Comment by prorounak2005** [comment]
I cannot use the whonix live mode in virtualbox. I dont know why.

**Comment by adrelanos** [comment]
https://forums.whonix.org/t/bullseye-live-boot-needs-grub-disable-linux-uuid-true-parameter-in-etc-grub-d-11-linux-live/9066/6
