### ISSUE TITLE
Download Page Not Working!!!

### ISSUE THREAD

**Issue by mohabgabber** [Whonix/Whonix#443]
i've been trying to download whonix but the website isn't working, it gives an internal error when accessing this [PAGE](https://www.whonix.org/wiki/VirtualBox) 
here is a screenshot

![Screenshot](https://user-images.githubusercontent.com/78929105/143681680-5d1c7982-803d-41c7-8706-a5f413000a3c.png)

**Comment by Samisafool** [comment]
Same here. bunch of ppl on reddit are having this too.

**Comment by adrelanos** [comment]
Fixed.
