### ISSUE TITLE
Verifying Tor version 11.0.3

### ISSUE THREAD

**Issue by Rspigler** [Whonix/Whonix#445]
I keep getting errors trying to verify the new version of Tor Browser version (11.0.3) (using the Tor Browser Downloader).  I am updating from 11.0.2

> 
> ERROR: Digital signature (GPG) could NOT be verified. 
> Tor Browser update failed! Try again later. 
> gpg_bash_lib_output_alright_status: 
> gpg_bash_lib_output_failure: 
> gpg_bash_lib_output_diagnostic_message: 
> gpg_bash_lib_internal_gpg_verify_status_fd_file: /var/cache/tb-binary/.cache/tb/gpgtmpdir/gpg_bash_lib_internal_gpg_verify_status_fd_file
> gpg_bash_lib_internal_gpg_verify_output_file: /var/cache/tb-binary/.cache/tb/gpgtmpdir/gpg_bash_lib_internal_gpg_verify_output_file
> gpg_bash_lib_output_gpg_import_output:
> gpg: keybox '/var/cache/tb-binary/.cache/tb/gpgtmpdir/pubring.kbx' created
> gpg: /var/cache/tb-binary/.cache/tb/gpgtmpdir/trustdb.gpg: trustdb created
> gpg: key 4E2C6E8793298290: public key "Tor Browser Developers (signing key) " imported
> gpg: Total number processed: 1
> gpg: imported: 1
> gpg_bash_lib_output_gpg_verify_output:
> gpg: Signature made Fri 17 Dec 2021 02:18:25 PM UTC
> gpg: using RSA key 3D1B08D7D5F58676B838DC925601A3DC64D6E363
> gpg: Can't check signature: No public key
> gpg_bash_lib_output_gpg_verify_status_fd_output:

I am running Qubes 4.0 with completely updated templates (Fedora 34, Debian 11, Whonix 16).

**Comment by adrelanos** [comment]
https://forums.whonix.org/t/tor-browser-downloader-needs-to-update-its-pgp-keys/13077

https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/40759

**Comment by Rspigler** [comment]
Will continue discussion on forum
