### ISSUE TITLE
Time Privacy

### ISSUE THREAD

**Issue by adrelanos** [Whonix/Whonix#5]
Done in git master:

* Wrote a wrapper to obfuscate the time: https://github.com/adrelanos/timeprivacy. Proposed it and got it merged upstream with faketime: https://github.com/wolfcw/libfaketime/pull/16.
* Added the timeprivacy script to Whonix /usr/local/bin/timeprivacy already because it will take a while until its in Debian.
* Added configuration file folder /etc/whonix.d/.
* Added it to uwt wrapper /usr/local/bin/uwtwrapper.

Left to do:

* User documentation for next Whonix version about this new experimental feature, how to enable, how to use.

**Comment by JasonJAyalaP** [comment]
https://phabricator.whonix.org/T67
