### ISSUE TITLE
document how to use the Tor and obfsproxy from the Pluggable Transports Bundle in Whonix-Gateway

### ISSUE THREAD

**Issue by adrelanos** [Whonix/Whonix#53]
At the moment Whonix 0.5.6 does not contain obfs3. And in censored countries its difficult to obtain obfs3 for Whonix-Gateway, since it downloads over Tor, which isn't reachable in the first place.

If there were instructions how to get the Tor and obfsproxy from the Pluggable Transports Bundle for use inside Whonix-Gateway, that would help to get out of the deadlock.

Same may happen for Whonix 6 in future.

**Comment by JasonJAyalaP** [comment]
@adrelanos  
What exactly is "still very much worth doing"? Is it already included https://github.com/Whonix/Whonix/issues/167?

**Comment by adrelanos** [comment]
TODO:

* document how to use TBB as "system Tor" inside Whonix-Gateway

We are working somewhat on that in the forums at the moment. Although the goal is to do this for the user. Not sure how long it will take, if we need to refer to a "user must do itself" solution in meanwhile.

https://www.whonix.org/forum/index.php/topic,720.0.html

**Comment by WhonixQubes** [comment]
Interesting discussion on tor-talk from Roger about prioritization of Tails implementation for pluggable transports...

- https://lists.torproject.org/pipermail/tor-talk/2015-January/036549.html
- https://lists.torproject.org/pipermail/tor-talk/2015-January/036559.html

**Comment by JasonJAyalaP** [comment]
https://phabricator.whonix.org/T116
