### ISSUE TITLE
document 32 bit vs 64 bit

### ISSUE THREAD

**Issue by adrelanos** [Whonix/Whonix#85]
A user in asked [in the forum](https://www.whonix.org/wiki/Special:AWCforum/st/id131/Your_internet_connection_appears....html) if Whonix is 32 bit or 64 bit.

Legitimate question. To my knowledge neither on the Download page nor anywhere inside Whonix this is being made clear. At the moment there are only 32 bit builds (may change in future) and they run on both, 64 bit and 32 bit machines. We ship a linux-i386 kernel (for compatibility) and a i686-pae kernel (default). The distinguision between i386 kernel (for compatibility) and a i686-pae doesn't make it any easier.

To complicate things further, the linux-image-amd64 kernel supports both Intel 64 bit and AMD 64 bit. We're not having 64 bit builds yet, so this isn't of concern yet, I just added it, so we won't come up with a non-extensible solution.

What would be good places to note that Whonix is currently 32 bit? (Users need to know, that they're based on Debian Testing/Jessie i386, if they want to manually update Tor Browser or want to install other custom packages, which aren't in Debian or Whonix repository (such as i2p, etc.)

In file name?
a) Whonix-Gateway-6_i386+i686-pae.ova?
b) Or just Whonix-Gateway-6_i386? (And surprise, surprise, it comes with i686-pae kernel by default.)

I think b) Whonix-Gateway-6_i386.ova isn't most accurate, but best compromise of accuracy and simplicity for a file name.

On download page?
Also add i386?
I am a bit afraid, that this may confuse users. One seeing i386 or i686 or 32 bit may falsely get the impression "duh, I've got 64 bit, won't work for me".

Inside Whonix?
~/.bashrc might be a good place?
Perhaps adding that information to the desktop background?
Add it to whonixcheck's window title?

**Comment by JasonJAyalaP** [comment]
https://phabricator.whonix.org/T91
