### ISSUE TITLE
Change KDE Theme and KDE Mouse Theme

### ISSUE THREAD

**Issue by adrelanos** [Whonix/Whonix#9]
Purpose: Prevent confusion of host desktop with Whonix-Gateway desktop or Whonix-Workstation desktop.

It's easy to do by manually using a mouse, but I haven't found out how to do it shipping a configuration file.

After being done, update https://www.whonix.org/wiki/Dev/KDE from TODO to Done.

**Comment by JasonJAyalaP** [comment]
https://phabricator.whonix.org/T69
